# create a data frame from Altman's financial data for Dillards dept store

In [8]:
# https://www.sec.gov/dera/data/financial-statement-data-sets.html
import os
import pandas as pd
import numpy as np
from re import search

# 0000028917-20-000127	28917	DILLARD'S, INC.	5311	US	AR	LITTLE ROCK	72201	1600 CANTRELL RD		5013765200	US	AR	LITTLE ROCK	72201	1600 CANTRELL ROAD		US	AR	710388071	DILLARDS INC	19980622	1-LAF	0	0131	10-Q	20200430	2020	Q1	20200605	2020-06-05 17:18:00.0	0	1	dds-05022020x10q_htm.xml	1	

num_target = "0000028917-20-000127"
dirname = "2020q2"
file =["num.txt","pre.txt","sub.txt","tag.txt"][0]

with open(os.path.join(dirname,file), 'r') as f:
    d = f.readlines()

In [9]:
print(len(d))
d0 = [t for t in d if search("^"+ num_target, t)]
d0

2197733

['0000028917-20-000127\tOperatingLeasesRentExpenseNet\tus-gaap/2018\t\t20200430\t1\tUSD\t5550000.0000\t\n',
 '0000028917-20-000127\tOperatingLeasesRentExpenseNet\tus-gaap/2018\t\t20190430\t1\tUSD\t6118000.0000\t\n',
 '0000028917-20-000127\tOperatingLeaseWeightedAverageDiscountRatePercent\tus-gaap/2018\t\t20200430\t0\tpure\t0.0660\t\n',
 '0000028917-20-000127\tOtherAssetsCurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t55223000.0000\t\n',
 '0000028917-20-000127\tOtherAssetsCurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t59838000.0000\t\n',
 '0000028917-20-000127\tOtherAssetsCurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t66015000.0000\t\n',
 '0000028917-20-000127\tOtherAssetsNoncurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t75314000.0000\t\n',
 '0000028917-20-000127\tOtherAssetsNoncurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t76075000.0000\t\n',
 '0000028917-20-000127\tOtherAssetsNoncurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t79418000.0000\t\n',
 '0000028917-20-000127\tDeferredTaxAssetsOperatingLossCarryforwards\tus-gaap/2018\t\t20200430\t0\tUSD\t4908000.0000\t\n',
 '0000028917-20-000127\tDeferredTaxAssetsOperatingLossCarryforwards\tus-gaap/2018\t\t20190430\t0\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tOtherComprehensiveIncomeLossNetOfTax\tus-gaap/2018\t\t20200430\t1\tUSD\t431000.0000\t\n',
 '0000028917-20-000127\tOtherComprehensiveIncomeLossPensionAndOtherPostretirementBenefitPlansAdjustmentNetOfTax\tus-gaap/2018\t\t20200430\t1\tUSD\t-431000.0000\t\n',
 '0000028917-20-000127\tOtherComprehensiveIncomeLossPensionAndOtherPostretirementBenefitPlansAdjustmentNetOfTax\tus-gaap/2018\t\t20190430\t1\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tOtherComprehensiveIncomeLossPensionAndOtherPostretirementBenefitPlansTax\tus-gaap/2018\t\t20200430\t1\tUSD\t138000.0000\t\n',
 '0000028917-20-000127\tOtherComprehensiveIncomeLossPensionAndOtherPostretirementBenefitPlansTax\tus-gaap/2018\t\t20190430\t1\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tDeferredTaxLiabilitiesOther\tus-gaap/2018\t\t20200430\t0\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tDeferredTaxLiabilitiesOther\tus-gaap/2018\t\t20200131\t0\tUSD\t3490000.0000\t\n',
 '0000028917-20-000127\tDeferredTaxLiabilitiesOther\tus-gaap/2018\t\t20190430\t0\tUSD\t17590000.0000\t\n',
 '0000028917-20-000127\tDefinedBenefitPlanServiceCost\tus-gaap/2018\t\t20200430\t1\tUSD\t1090000.0000\t\n',
 '0000028917-20-000127\tDefinedBenefitPlanServiceCost\tus-gaap/2018\t\t20190430\t1\tUSD\t905000.0000\t\n',
 '0000028917-20-000127\tDefinedBenefitPlanAmortizationOfGainsLosses\tus-gaap/2018\t\t20200430\t1\tUSD\t-569000.0000\t\n',
 '0000028917-20-000127\tDefinedBenefitPlanAmortizationOfGainsLosses\tus-gaap/2018\t\t20190430\t1\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tDefinedBenefitPlanContributionsByEmployer\tus-gaap/2018\t\t20200430\t1\tUSD\t1400000.0000\t\n',
 '0000028917-20-000127\tAccountsPayableAndAccruedLiabilitiesCurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t1134258000.0000\t\n',
 '0000028917-20-000127\tAccountsPayableAndAccruedLiabilitiesCurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t1055891000.0000\t\n',
 '0000028917-20-000127\tAccountsPayableAndAccruedLiabilitiesCurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t892789000.0000\t\n',
 '0000028917-20-000127\tLineOfCreditFacilityMaximumBorrowingCapacity\tus-gaap/2018\t\t20200430\t0\tUSD\t800000000.0000\t\n',
 '0000028917-20-000127\tLineOfCreditFacilityRemainingBorrowingCapacity\tus-gaap/2018\t\t20200430\t0\tUSD\t779000000.0000\t\n',
 '0000028917-20-000127\tDefinedBenefitPlanInterestCost\tus-gaap/2018\t\t20200430\t1\tUSD\t1536000.0000\t\n',
 '0000028917-20-000127\tDefinedBenefitPlanInterestCost\tus-gaap/2018\t\t20190430\t1\tUSD\t1917000.0000\t\n',
 '0000028917-20-000127\tDefinedBenefitPlanNetPeriodicBenefitCost\tus-gaap/2018\t\t20200430\t1\tUSD\t3195000.0000\t\n',
 '0000028917-20-000127\tDefinedBenefitPlanNetPeriodicBenefitCost\tus-gaap/2018\t\t20190430\t1\tUSD\t2822000.0000\t\n',
 '0000028917-20-000127\tLineOfCreditFacilityUnusedCapacityCommitmentFeePercentage\tus-gaap/2018\t\t20200430\t1\tpure\t0.0030\t\n',
 '0000028917-20-000127\tIncreaseDecreaseInOtherCurrentAssets\tus-gaap/2018\t\t20200430\t1\tUSD\t-4615000.0000\t\n',
 '0000028917-20-000127\tIncreaseDecreaseInOtherCurrentAssets\tus-gaap/2018\t\t20190430\t1\tUSD\t-2738000.0000\t\n',
 '0000028917-20-000127\tIncreaseDecreaseInOtherOperatingAssets\tus-gaap/2018\t\t20200430\t1\tUSD\t-1162000.0000\t\n',
 '0000028917-20-000127\tIncreaseDecreaseInOtherOperatingAssets\tus-gaap/2018\t\t20190430\t1\tUSD\t2149000.0000\t\n',
 '0000028917-20-000127\tDepreciationAndAmortization\tus-gaap/2018\t\t20200430\t1\tUSD\t50901000.0000\t\n',
 '0000028917-20-000127\tDepreciationAndAmortization\tus-gaap/2018\t\t20190430\t1\tUSD\t52364000.0000\t\n',
 '0000028917-20-000127\tContractWithCustomerLiability\tus-gaap/2018\t\t20200430\t0\tUSD\t67107000.0000\t\n',
 '0000028917-20-000127\tContractWithCustomerLiability\tus-gaap/2018\t\t20200131\t0\tUSD\t75229000.0000\t\n',
 '0000028917-20-000127\tContractWithCustomerLiability\tus-gaap/2018\t\t20190430\t0\tUSD\t64934000.0000\t\n',
 '0000028917-20-000127\tContractWithCustomerLiability\tus-gaap/2018\t\t20190131\t0\tUSD\t72852000.0000\t\n',
 '0000028917-20-000127\tContractWithCustomerLiabilityRevenueRecognized\tus-gaap/2018\t\t20200430\t1\tUSD\t18900000.0000\t\n',
 '0000028917-20-000127\tContractWithCustomerLiabilityRevenueRecognized\tus-gaap/2018\t\t20190430\t1\tUSD\t24800000.0000\t\n',
 '0000028917-20-000127\tAssets\tus-gaap/2018\t\t20200430\t0\tUSD\t3342345000.0000\t\n',
 '0000028917-20-000127\tAssets\tus-gaap/2018\t\t20200131\t0\tUSD\t3430257000.0000\t\n',
 '0000028917-20-000127\tAssets\tus-gaap/2018\t\t20190430\t0\tUSD\t3778988000.0000\t\n',
 '0000028917-20-000127\tAssetsCurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t1779670000.0000\t\n',
 '0000028917-20-000127\tAssetsCurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t1848082000.0000\t\n',
 '0000028917-20-000127\tAssetsCurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t2094944000.0000\t\n',
 '0000028917-20-000127\tIncreaseDecreaseInRetailRelatedInventories\tus-gaap/2018\t\t20200430\t1\tUSD\t105306000.0000\t\n',
 '0000028917-20-000127\tIncreaseDecreaseInRetailRelatedInventories\tus-gaap/2018\t\t20190430\t1\tUSD\t304164000.0000\t\n',
 '0000028917-20-000127\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments\tus-gaap/2018\t\t20190430\t1\tUSD\t100772000.0000\t\n',
 '0000028917-20-000127\tIncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments\tus-gaap/2018\t\t20200430\t1\tUSD\t-228145000.0000\t\n',
 '0000028917-20-000127\tIncomeTaxesReceivable\tus-gaap/2018\t\t20200430\t0\tUSD\t39176000.0000\t\n',
 '0000028917-20-000127\tIncomeTaxesReceivable\tus-gaap/2018\t\t20200131\t0\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tIncomeTaxesReceivable\tus-gaap/2018\t\t20190430\t0\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tIncomeTaxExpenseBenefit\tus-gaap/2018\t\t20200430\t1\tUSD\t-66170000.0000\t\n',
 '0000028917-20-000127\tIncomeTaxExpenseBenefit\tus-gaap/2018\t\t20190430\t1\tUSD\t22170000.0000\t\n',
 '0000028917-20-000127\tCommitmentsAndContingencies\tus-gaap/2018\t\t20200430\t0\tUSD\t\t\n',
 '0000028917-20-000127\tCommitmentsAndContingencies\tus-gaap/2018\t\t20200131\t0\tUSD\t\t\n',
 '0000028917-20-000127\tCommonStockDividendsPerShareDeclared\tus-gaap/2018\t\t20200430\t1\tUSD\t0.1500\t\n',
 '0000028917-20-000127\tCommonStockDividendsPerShareDeclared\tus-gaap/2018\t\t20190430\t1\tUSD\t0.1000\t\n',
 '0000028917-20-000127\tCommonStockValue\tus-gaap/2018\t\t20200430\t0\tUSD\t1239000.0000\t\n',
 '0000028917-20-000127\tCommonStockValue\tus-gaap/2018\t\t20200131\t0\tUSD\t1239000.0000\t\n',
 '0000028917-20-000127\tCommonStockValue\tus-gaap/2018\t\t20190430\t0\tUSD\t1239000.0000\t\n',
 '0000028917-20-000127\tAccruedIncomeTaxesCurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tAccruedIncomeTaxesCurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t22158000.0000\t\n',
 '0000028917-20-000127\tAccruedIncomeTaxesCurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t28961000.0000\t\n',
 '0000028917-20-000127\tIncreaseDecreaseInAccountsPayableAndOtherOperatingLiabilities\tus-gaap/2018\t\t20200430\t1\tUSD\t161463000.0000\t\n',
 '0000028917-20-000127\tIncreaseDecreaseInAccountsPayableAndOtherOperatingLiabilities\tus-gaap/2018\t\t20190430\t1\tUSD\t204259000.0000\t\n',
 '0000028917-20-000127\tIncreaseDecreaseInAccountsReceivable\tus-gaap/2018\t\t20200430\t1\tUSD\t-1196000.0000\t\n',
 '0000028917-20-000127\tIncreaseDecreaseInAccountsReceivable\tus-gaap/2018\t\t20190430\t1\tUSD\t-1990000.0000\t\n',
 '0000028917-20-000127\tJuniorSubordinatedDebentureOwedToUnconsolidatedSubsidiaryTrustNoncurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t200000000.0000\t\n',
 '0000028917-20-000127\tJuniorSubordinatedDebentureOwedToUnconsolidatedSubsidiaryTrustNoncurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t200000000.0000\t\n',
 '0000028917-20-000127\tJuniorSubordinatedDebentureOwedToUnconsolidatedSubsidiaryTrustNoncurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t200000000.0000\t\n',
 '0000028917-20-000127\tComprehensiveIncomeNetOfTax\tus-gaap/2018\t\t20200430\t1\tUSD\t-161544000.0000\t\n',
 '0000028917-20-000127\tComprehensiveIncomeNetOfTax\tus-gaap/2018\t\t20190430\t1\tUSD\t78602000.0000\t\n',
 '0000028917-20-000127\tNetCashProvidedByUsedInFinancingActivities\tus-gaap/2018\t\t20200430\t1\tUSD\t-76054000.0000\t\n',
 '0000028917-20-000127\tNetCashProvidedByUsedInFinancingActivities\tus-gaap/2018\t\t20190430\t1\tUSD\t-18294000.0000\t\n',
 '0000028917-20-000127\tNetCashProvidedByUsedInInvestingActivities\tus-gaap/2018\t\t20200430\t1\tUSD\t-19904000.0000\t\n',
 '0000028917-20-000127\tNetCashProvidedByUsedInInvestingActivities\tus-gaap/2018\t\t20190430\t1\tUSD\t-5087000.0000\t\n',
 '0000028917-20-000127\tNetCashProvidedByUsedInOperatingActivities\tus-gaap/2018\t\t20200430\t1\tUSD\t-111125000.0000\t\n',
 '0000028917-20-000127\tNetCashProvidedByUsedInOperatingActivities\tus-gaap/2018\t\t20190430\t1\tUSD\t48357000.0000\t\n',
 '0000028917-20-000127\tNetIncomeLoss\tus-gaap/2018\t\t20190430\t1\tUSD\t78602000.0000\t\n',
 '0000028917-20-000127\tNetIncomeLoss\tus-gaap/2018\t\t20200430\t1\tUSD\t-161975000.0000\t\n',
 '0000028917-20-000127\tConcentrationRiskPercentage1\tus-gaap/2018\t\t20200430\t1\tpure\t1.0000\t\n',
 '0000028917-20-000127\tConcentrationRiskPercentage1\tus-gaap/2018\t\t20190430\t1\tpure\t1.0000\t\n',
 '0000028917-20-000127\tCapitalExpendituresIncurredButNotYetPaid\tus-gaap/2018\t\t20200430\t1\tUSD\t8314000.0000\t\n',
 '0000028917-20-000127\tCapitalExpendituresIncurredButNotYetPaid\tus-gaap/2018\t\t20190430\t1\tUSD\t6657000.0000\t\n',
 '0000028917-20-000127\tAccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment\tus-gaap/2018\t\t20200430\t0\tUSD\t2385686000.0000\t\n',
 '0000028917-20-000127\tAccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment\tus-gaap/2018\t\t20200131\t0\tUSD\t2236728000.0000\t\n',
 '0000028917-20-000127\tAccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment\tus-gaap/2018\t\t20190430\t0\tUSD\t2259145000.0000\t\n',
 '0000028917-20-000127\tPaymentsForRepurchaseOfCommonStock\tus-gaap/2018\t\t20200430\t1\tUSD\t69152000.0000\t\n',
 '0000028917-20-000127\tPaymentsForRepurchaseOfCommonStock\tus-gaap/2018\t\t20190430\t1\tUSD\t15440000.0000\t\n',
 '0000028917-20-000127\tLongTermDebtNoncurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t365743000.0000\t\n',
 '0000028917-20-000127\tLongTermDebtNoncurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t365709000.0000\t\n',
 '0000028917-20-000127\tLongTermDebtNoncurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t365603000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseInterestExpense\tus-gaap/2018\t\t20200430\t1\tUSD\t79000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseInterestExpense\tus-gaap/2018\t\t20190430\t1\tUSD\t135000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseInterestPaymentOnLiability\tus-gaap/2018\t\t20200430\t1\tUSD\t79000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseInterestPaymentOnLiability\tus-gaap/2018\t\t20190430\t1\tUSD\t135000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiability\tus-gaap/2018\t\t20200430\t0\tUSD\t1637000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityCurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t1109000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityCurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t1219000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityCurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t1022000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityNoncurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t528000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityNoncurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t695000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityNoncurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t1636000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityPaymentsDue\tus-gaap/2018\t\t20200430\t0\tUSD\t1797000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityPaymentsDueAfterYearFive\tus-gaap/2018\t\t20200430\t0\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityPaymentsDueYearFive\tus-gaap/2018\t\t20200430\t0\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityPaymentsDueYearFour\tus-gaap/2018\t\t20200430\t0\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityPaymentsDueYearThree\tus-gaap/2018\t\t20200430\t0\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityPaymentsDueYearTwo\tus-gaap/2018\t\t20200430\t0\tUSD\t726000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityPaymentsRemainderOfFiscalYear\tus-gaap/2018\t\t20200430\t0\tUSD\t1071000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseLiabilityUndiscountedExcessAmount\tus-gaap/2018\t\t20200430\t0\tUSD\t160000.0000\t\n',
 '0000028917-20-000127\tFinanceLeasePrincipalPayments\tus-gaap/2018\t\t20200430\t1\tUSD\t277000.0000\t\n',
 '0000028917-20-000127\tFinanceLeasePrincipalPayments\tus-gaap/2018\t\t20190430\t1\tUSD\t222000.0000\t\n',
 '0000028917-20-000127\tAccumulatedOtherComprehensiveIncomeLossNetOfTax\tus-gaap/2018\t\t20200430\t0\tUSD\t-30628000.0000\t\n',
 '0000028917-20-000127\tAccumulatedOtherComprehensiveIncomeLossNetOfTax\tus-gaap/2018\t\t20200131\t0\tUSD\t-31059000.0000\t\n',
 '0000028917-20-000127\tAccumulatedOtherComprehensiveIncomeLossNetOfTax\tus-gaap/2018\t\t20190430\t0\tUSD\t-12809000.0000\t\n',
 '0000028917-20-000127\tProceedsFromEquityMethodInvestmentDividendsOrDistributionsReturnOfCapital\tus-gaap/2018\t\t20200430\t1\tUSD\t215000.0000\t\n',
 '0000028917-20-000127\tProceedsFromEquityMethodInvestmentDividendsOrDistributionsReturnOfCapital\tus-gaap/2018\t\t20190430\t1\tUSD\t215000.0000\t\n',
 '0000028917-20-000127\tLesseeOperatingLeaseLiabilityPaymentsDue\tus-gaap/2018\t\t20200430\t0\tUSD\t58990000.0000\t\n',
 '0000028917-20-000127\tLesseeOperatingLeaseLiabilityPaymentsDueAfterYearFive\tus-gaap/2018\t\t20200430\t0\tUSD\t15916000.0000\t\n',
 '0000028917-20-000127\tLesseeOperatingLeaseLiabilityPaymentsDueYearFive\tus-gaap/2018\t\t20200430\t0\tUSD\t3649000.0000\t\n',
 '0000028917-20-000127\tLesseeOperatingLeaseLiabilityPaymentsDueYearFour\tus-gaap/2018\t\t20200430\t0\tUSD\t4406000.0000\t\n',
 '0000028917-20-000127\tLesseeOperatingLeaseLiabilityPaymentsDueYearThree\tus-gaap/2018\t\t20200430\t0\tUSD\t7696000.0000\t\n',
 '0000028917-20-000127\tLesseeOperatingLeaseLiabilityPaymentsDueYearTwo\tus-gaap/2018\t\t20200430\t0\tUSD\t14048000.0000\t\n',
 '0000028917-20-000127\tLesseeOperatingLeaseLiabilityPaymentsRemainderOfFiscalYear\tus-gaap/2018\t\t20200430\t0\tUSD\t13275000.0000\t\n',
 '0000028917-20-000127\tLesseeOperatingLeaseLiabilityUndiscountedExcessAmount\tus-gaap/2018\t\t20200430\t0\tUSD\t10757000.0000\t\n',
 '0000028917-20-000127\tPaymentsOfDividendsCommonStock\tus-gaap/2018\t\t20200430\t1\tUSD\t3705000.0000\t\n',
 '0000028917-20-000127\tPaymentsOfDividendsCommonStock\tus-gaap/2018\t\t20190430\t1\tUSD\t2632000.0000\t\n',
 '0000028917-20-000127\tPaymentsOfFinancingCosts\tus-gaap/2018\t\t20200430\t1\tUSD\t2920000.0000\t\n',
 '0000028917-20-000127\tPaymentsOfFinancingCosts\tus-gaap/2018\t\t20190430\t1\tUSD\t0.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseRightOfUseAsset\tus-gaap/2018\t\t20200430\t0\tUSD\t564000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseRightOfUseAsset\tus-gaap/2018\t\t20200131\t0\tUSD\t670000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseRightOfUseAsset\tus-gaap/2018\t\t20190430\t0\tUSD\t987000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseRightOfUseAssetAmortization\tus-gaap/2018\t\t20200430\t1\tUSD\t106000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseRightOfUseAssetAmortization\tus-gaap/2018\t\t20190430\t1\tUSD\t106000.0000\t\n',
 '0000028917-20-000127\tFinanceLeaseWeightedAverageDiscountRatePercent\tus-gaap/2018\t\t20200430\t0\tpure\t0.1400\t\n',
 '0000028917-20-000127\tCapitalLeaseObligationsCurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t1109000.0000\t\n',
 '0000028917-20-000127\tCapitalLeaseObligationsCurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t1219000.0000\t\n',
 '0000028917-20-000127\tCapitalLeaseObligationsCurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t1022000.0000\t\n',
 '0000028917-20-000127\tCapitalLeaseObligationsNoncurrent\tus-gaap/2018\t\t20200430\t0\tUSD\t528000.0000\t\n',
 '0000028917-20-000127\tCapitalLeaseObligationsNoncurrent\tus-gaap/2018\t\t20200131\t0\tUSD\t695000.0000\t\n',
 '0000028917-20-000127\tCapitalLeaseObligationsNoncurrent\tus-gaap/2018\t\t20190430\t0\tUSD\t1636000.0000\t\n',
 '0000028917-20-000127\tGainLossOnDispositionOfAssets1\tus-gaap/2018\t\t20200430\t1\tUSD\t19000.0000\t\n',
 '0000028917-20-000127\tGainLossOnDispositionOfAssets1\tus-gaap/2018\t\t20190430\t1\tUSD\t7400000.0000\t\n',
 '0000028917-20-000127\tAdditionalPaidInCapitalCommonStock\tus-gaap/2018\t\t20200430\t0\tUSD\t951726000.0000\t\n',
 '0000028917-20-000127\tAdditionalPaidInCapitalCommonStock\tus-gaap/2018\t\t20200131\t0\tUSD\t951726000.0000\t\n',
 '0000028917-20-000127\tAdditionalPaidInCapitalCommonStock\tus-gaap/2018\t\t20190430\t0\tUSD\t948835000.0000\t\n',
 '0000028917-20-000127\tLettersOfCreditOutstandingAmount\tus-gaap/2018\t\t20200430\t0\tUSD\t21000000.0000\t\n',
 '0000028917-20-000127\tPaymentsToAcquirePropertyPlantAndEquipment\tus-gaap/2018\t\t20200430\t1\tUSD\t20230000.0000\t\n',
 '0000028917-20-000127\tPaymentsToAcquirePropertyPlantAndEquipment\tus-gaap/2018\t\t20190430\t1\tUSD\t18739000.0000\t\n',
 '0000028917-20-000127\tCashAndCashEquivalentsAtCarryingValue\tus-gaap/2018\t\t20190430\t0\tUSD\t139802000.0000\t\n',
 '0000028917-20-000127\tCashAndCashEquivalentsAtCarryingValue\tus-gaap/2018\t\t20200131\t0\tUSD\t277077000.0000\t\n',
 '0000028917-20-000127\tCashAndCashEquivalentsAtCarryingValue\tus-gaap/2018\t\t20200430\t0\tUSD\t69994000.0000\t\n',
 '0000028917-20-000127\tTreasuryStockAcquiredAverageCostPerShare\tus-gaap/2018\t\t20200430\t1\tUSD\t61910.0000\t\n',
 '0000028917-20-000127\tTreasuryStockAcquiredAverageCostPerShare\tus-gaap/2018\t\t20190430\t1\tUSD\t70.8500\t\n',
 '0000028917-20-000127\tTreasuryStockSharesAcquired\tus-gaap/2018\t\t20200430\t1\tshares\t998742.0000\t\n',
 '0000028917-20-000127\tTreasuryStockSharesAcquired\tus-gaap/2018\t\t20190430\t1\tshares\t246158.0000\t\n',
 '0000028917-20-000127\tTreasuryStockValue\tus-gaap/2018\t\t20200430\t0\tUSD\t3916970000.0000\t\n',
 '0000028917-20-000127\tTreasuryStockValue\tus-gaap/2018\t\t20200131\t0\tUSD\t3855141000.0000\t\n',
 '0000028917-20-000127\tTreasuryStockValue\tus-gaap/2018\t\t20190430\t0\tUSD\t3734330000.0000\t\n',
 '0000028917-20-000127\tCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents\tus-gaap/2018\t\t20200131\t0\tUSD\t277077000.0000\t\n',
 '0000028917-20-000127\tCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents\tus-gaap/2018\t\t20190131\t0\tUSD\t123509000.0000\t\n',
 '0000028917-20-000127\tCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents\tus-gaap/2018\t\t20200430\t0\tUSD\t69994000.0000\t\n',
 '0000028917-20-000127\tCashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents\tus-gaap/2018\t\t20190430\t0\tUSD\t148485000.0000\t\n',

In [10]:
d[0]

'adsh\ttag\tversion\tcoreg\tddate\tqtrs\tuom\tvalue\tfootnote\n'

In [11]:
rec = pd.DataFrame([r.split('\t') for r in d0], columns=d[0].split('\t'))
print(rec.shape)
rec[:10]

(315, 9)

,adsh,tag,version,coreg,ddate,qtrs,uom,value,footnote\n
0,0000028917-20-000127,OperatingLeasesRentExpenseNet,us-gaap/2018,,20200430,1,USD,5550000.0000,\n
1,0000028917-20-000127,OperatingLeasesRentExpenseNet,us-gaap/2018,,20190430,1,USD,6118000.0000,\n
2,0000028917-20-000127,OperatingLeaseWeightedAverageDiscountRatePercent,us-gaap/2018,,20200430,0,pure,0.0660,\n
3,0000028917-20-000127,OtherAssetsCurrent,us-gaap/2018,,20200430,0,USD,55223000.0000,\n
4,0000028917-20-000127,OtherAssetsCurrent,us-gaap/2018,,20200131,0,USD,59838000.0000,\n
5,0000028917-20-000127,OtherAssetsCurrent,us-gaap/2018,,20190430,0,USD,66015000.0000,\n
6,0000028917-20-000127,OtherAssetsNoncurrent,us-gaap/2018,,20200430,0,USD,75314000.0000,\n
7,0000028917-20-000127,OtherAssetsNoncurrent,us-gaap/2018,,20200131,0,USD,76075000.0000,\n
8,0000028917-20-000127,OtherAssetsNoncurrent,us-gaap/2018,,20190430,0,USD,79418000.0000,\n
9,0000028917-20-000127,DeferredTaxAssetsOperatingLossCarryforwards,us-gaap/2018,,20200430,0,USD,4908000.0000,\n

#

In [12]:
from collections import Counter

print(Counter(rec['adsh']).most_common())

print(Counter(rec['ddate']).most_common())
print()
print(rec.shape, len(Counter(rec['tag'])), Counter(rec['uom']),Counter(rec['qtrs']))
print()

target_date = ['20200430','20200131','20190131'][0]
rec2020 = rec[rec['ddate'] == target_date]

print(rec2020.shape, len(Counter(rec2020['tag'])), Counter(rec2020['uom']),Counter(rec2020['qtrs']))
display(rec2020)

Counter(rec2020['ddate']), Counter(rec2020['uom']),Counter(rec2020['qtrs'])

[('0000028917-20-000127', 315)]
[('20200430', 156), ('20190430', 108), ('20200131', 44), ('20190131', 6), ('20171231', 1)]

(315, 9) 158 Counter({'USD': 295, 'pure': 12, 'shares': 7, 'segment': 1}) Counter({'0': 177, '1': 137, '4': 1})

(156, 9) 156 Counter({'USD': 142, 'pure': 9, 'shares': 4, 'segment': 1}) Counter({'0': 83, '1': 73})

,adsh,tag,version,coreg,ddate,qtrs,uom,value,footnote\n
0,0000028917-20-000127,OperatingLeasesRentExpenseNet,us-gaap/2018,,20200430,1,USD,5550000.0000,\n
2,0000028917-20-000127,OperatingLeaseWeightedAverageDiscountRatePercent,us-gaap/2018,,20200430,0,pure,0.0660,\n
3,0000028917-20-000127,OtherAssetsCurrent,us-gaap/2018,,20200430,0,USD,55223000.0000,\n
6,0000028917-20-000127,OtherAssetsNoncurrent,us-gaap/2018,,20200430,0,USD,75314000.0000,\n
9,0000028917-20-000127,DeferredTaxAssetsOperatingLossCarryforwards,us-gaap/2018,,20200430,0,USD,4908000.0000,\n
...,...,...,...,...,...,...,...,...,...
306,0000028917-20-000127,RevenuefromContractswithCustomers,0000028917-20-000127,,20200430,1,USD,786655000.0000,\n
307,0000028917-20-000127,RevenueRecognizedpreviouslyrecordedinBillingsinexcessofcostsandestimatedearnings,0000028917-20-000127,,20200430,1,USD,4200000.0000,\n
309,0000028917-20-000127,RightofUseAssetsTotal,0000028917-20-000127,,20200430,0,USD,48416000.0000,\n
312,0000028917-20-000127,ServiceChargesAndOtherIncome,0000028917-20-000127,,20200430,1,USD,34921000.0000,\n
314,0000028917-20-000127,TaxbenefitrelatedtocarrybackprovisionoftheCARESAct,0000028917-20-000127,,20200430,1,USD,14800000.0000,\n

(Counter({'20200430': 156}),
 Counter({'USD': 142, 'pure': 9, 'shares': 4, 'segment': 1}),
 Counter({'0': 83, '1': 73}))

In [13]:
pd.set_option('max_colwidth',100)
rec2020.iloc[[i for i,r in enumerate(rec2020['tag']) if search('Revenue', r)],[1,3,5,6,7]]

,tag,coreg,qtrs,uom,value
44,ContractWithCustomerLiabilityRevenueRecognized,,1,USD,18900000.0000
188,RevenueRemainingPerformanceObligation,,0,USD,145400000.0000
211,CostOfRevenue,,1,USD,688469000.0000
218,Revenues,,1,USD,821576000.0000
306,RevenuefromContractswithCustomers,,1,USD,786655000.0000
307,RevenueRecognizedpreviouslyrecordedinBillingsinexcessofcostsandestimatedearnings,,1,USD,4200000.0000

# Altman’s z-score 
## X1=working capital/total assets
## X2=retained earnings/total assets
## X3=earning before interest & taxes/total assets
## X4=market value of equity/book value of liabilities
## X5=sales/total assets

#### Unlikely to default if
$Z = 1.2X_1 + 1.4X_2 + 3.3X_3 + 0.6X_4 + 0.999 > 3$
#### Z < 1.8 very high default probability

In [14]:
stats = dict([(t,float(v+'0')) for t,v in zip(rec2020['tag'], rec2020['value'])])

X1 = (stats['AssetsCurrent'] - stats['LiabilitiesCurrent']) / stats['Assets']
X2 = stats['RetainedEarningsAccumulatedDeficit'] / stats['Assets']
X3 = stats['ComprehensiveIncomeNetOfTax'] / stats['Assets']
X4 = stats['CommonStockValue'] / stats['LiabilitiesCurrent']
X5 = stats['ProceedsFromSalesOfAssetsInvestingActivities'] / stats['Assets']
X5 = stats['Revenues'] / stats['Assets']

for s in "X1,X2,X3,X4,X5".split(','):
    print(f"{s} = {eval(s):6.3f}")

altman_z = 1.2 * 𝑋1 + 1.4 * 𝑋2 + 3.3 * 𝑋3 + 0.6 * 𝑋4 + 0.999 * X5

print(f"\nZ = {altman_z:0.3f}\n")

for c,text in [(1.8, 'very high default prob'),(3.0,'"grey zone"'), (float('inf'),'unlikely to default')]:
    if altman_z < c:
        print(f"altman z = {altman_z:0.3f}, {text}")
        break

X1 =  0.212
X2 =  1.314
X3 = -0.048
X4 =  0.001
X5 =  0.246

Z = 2.180

altman z = 2.180, "grey zone"

debt = 'LongTermDebtNoncurrent'
earnings = 'Billingsinexcessofcostsandestimatedearningsonuncompletedcontractsconstructionsegment'
retained earnings ='RetainedEarningsAccumulatedDeficit'
stockvalue = 'StockholdersEquity'

Earnings Before Interest and Taxes = ComprehensiveIncomeNetOfTax

Billingsinexcessofcostsandestimatedearningsonuncompletedcontractsconstructionsegment - 

Working capital is defined as the difference between current assets and
current liabilities. AssetsCurrent - LiabilitiesCurrent

CommonStockValue
LiabilitiesAndStockholdersEquity	

x1: 'LiabilitiesAndStockholdersEquity', 'Assets'
x2: 'RetainedEarningsAccumulatedDeficit	', 'Assets'